{
 "title": "IoT Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_cpu_usage_percent", "legendFormat": "CPU Usage" }
   ]
  },
  {
   "title": "RAM Usage %",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(system_ram_usage_bytes / system_ram_total_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_network_transmit_bytes[$__rate_interval])",
     "legendFormat": "Network Traffic (in/out)"
    }
   ]
  },
  { "title": "Anomaly Simulation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Attack Type",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iot_attack_type_code", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CO2 Sensor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "iot_sensor_co2_ppm", "legendFormat": "CO2 Sensor" }
   ]
  },
  {
   "title": "Login Attack Attempts (in 1 Minute)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(iot_security_login_attempts_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}