{
 "title": "System Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "No. of CVEs in System Packages",
   "type": "barchart",
   "description": "Number of CVEs in System Packages installed by APT. Analyzed by grype.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({job=\"security/cve_scanner\"} | json | vulnerability_severity = \"Critical\" [$__auto]))",
     "legendFormat": "Critical"
    },
    {
     "direction": "backward",
     "expr": "count(rate({job=\"security/cve_scanner\"} | json | vulnerability_severity = `High` [$__auto]))",
     "legendFormat": "High"
    },
    {
     "direction": "backward",
     "expr": "count(rate({job=\"security/cve_scanner\"} | json | vulnerability_severity = `Medium` [$__auto]))",
     "legendFormat": "Medium"
    }
   ]
  },
  {
   "title": "CVEs in System Packages",
   "type": "table",
   "description": "CVEs in System Packages installed by APT.\nAnalyzed by grype.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"security/cve_scanner\"} | json",
     "legendFormat": "Critical"
    }
   ]
  },
  {
   "title": "Bootloader Errors",
   "type": "gauge",
   "description": "Errors derived from boot.log",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({instance=\"vbox\", filename=\"/var/log/boot.log\"} |~ `(?i)FAIL` | label_format level=detected_level [$__auto]))"
    }
   ]
  },
  {
   "title": "Journald Errors",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(rate({job=\"loki.source.journal.logs_integrations_integrations_node_exporter_journal_scrape\", service_name=\"loki.source.journal.logs_integrations_integrations_node_exporter_journal_scrape\", level=~\"error\"} !~ `(?i)decibel` !~ `(?i)freedesktop` [$__auto]))"
    }
   ]
  },
  {
   "title": "Bootloader Errors (Log View)",
   "type": "logs",
   "description": "Errors derived from boot.log",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=\"vbox\", filename=\"/var/log/boot.log\"} |= `FAILED` | label_format level=detected_level"
    }
   ]
  },
  {
   "title": "Journald Errors (Log View)",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"loki.source.journal.logs_integrations_integrations_node_exporter_journal_scrape\", service_name=\"loki.source.journal.logs_integrations_integrations_node_exporter_journal_scrape\", level=~\"error\"}"
    }
   ]
  }
 ]
}